### PR TITLE
Adding Dockerfile for 0.9.50 version

### LINKED ISSUE #13: Latest Docker image uses the outdated 0.9.1
Hey,

The official repository at https://hub.docker.com/r/cloudslang/cloudslang/ uses CS + Content release from the 0.9.1 version which is from December 2015.

How about we upgrade to the Dockerfile to 0.9.50?

### PR DESCRIPTION
**Pull request by lirantal**
Fixes #13 
- Adding Dockerfile for 0.9.50
- Updating the MAINTAINER clause from Meir Wahnon to CloudSlang team

### CODE REVIEW

**Comment by lirantal** [comment]
Do we also need/want to add the corresponding `dev/` directory? I'm not yet sure on the differences

**Comment by gituser173** [comment]
duplicate with #12

**Comment by levice14** [comment]
thanks @lirantal 

we will merge this PR first with basic Dockerfile and the #12 with the `dev` Dockerfile

**Comment by lirantal** [comment]
Thanks. I missed out the open PRs.
Good job @gituser173  :)

**Pull request merged**
